- name: Demo on Error Handling
  hosts: localhost
  tasks:
    - name: Some shell Command
      ansible.builtin.shell: lss
      ignore_error: yes

    - name: Print hello
      ansible.builtin.debug:
        msg: hai